---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openhab-system
resources:
  - storage.yaml
  - alloy-config.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: openhab-env
    literals:
      - tz="Europe/Amsterdam"
      - crypto_policy="limited"
      - extra_java_opts="-Duser.timezone=Europe/Amsterdam"
      - openhab_http_port="8080"
      - openhab_https_port="8443"
      - user_id="9001"
      - group_id="9001"
      - loki_url="http://loki-svc.monitoring-system.svc.cluster.local"
  - name: openhab-init
    files:
      - 20-add-allowed-ssh-keys
generatorOptions:
  disableNameSuffixHash: true
