# kustomize/production/configmaps.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhab-env
data:
  tz: "Europe/Amsterdam"
  crypto_policy: "unlimited"
  extra_java_opts: "-Duser.timezone=Europe/Amsterdam"
  loki_url: "http://loki-svc.logging.svc.cluster.local:3100/loki/api/v1/push"
