# openhab.git:kustomize/production/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
- ../base
- namespace.yaml
- ./services
patchesStrategicMerge:
- services-patch.yaml
- secrets-patch.yaml
- ingressroute-patch.yaml
- volumes-patch.yaml
- configmaps-patch.yaml
images:
  - name: openssh-server
    newTag: "1.0"
    newName: registry.moerman.online/library/openssh-server
  - name: configmap-reload
    newTag: "v0.13.1"
    newName: registry.moerman.online/library/configmap-reload
  - name: openhab
    newTag: 4.2.1
    newName: registry.moerman.online/library/openhab
  - name: alloy
    newTag: v1.3.1
    newName: registry.moerman.online/library/alloy
