# openhab.git:kustomize/production/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
- ../base
- namespace.yaml
replacements:
  - source:
      kind: Secret
      version: v1
      name: openhab
      # namespace: automation
      fieldPath: stringData.openhab_fqdn
    targets:
      - select:
          kind: IngressRoute
          version: traefik.io/v1alpha1
          name: openhab
          # namespace: automation
        fieldPaths:
          - spec.routes[0].match.value
patchesStrategicMerge:
- services.yaml
- secrets.yaml
patches:
  - target:
      version: traefik.io/v1alpha1
      kind: IngressRoute
      name: openhab
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`oh.moerman.online`)