---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-openhab
spec:
  path: ./openhab/openhab/base
  sourceRef:
    kind: GitRepository
    name: openhab
    namespace: flux-system
  interval: 2m
  prune: true
  wait: true
  dependsOn:
    - name: longhorn-system-longhorn
      namespace: flux-system
    - name: traefik-traefik
      namespace: flux-system
    - name: automation-influxdb
    - name: automation-mosquitto
