---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openhab-system
resources:
  - ./namespace.yaml
  - ./influxdb/kustomization-fluxCRD.yaml
  - ./mosquitto/kustomization-fluxCRD.yaml
  - ./openhab/kustomization-fluxCRD.yaml
