---
kind: Secret
apiVersion: v1
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: ${SECRET_INFLUXDB_INIT_USERNAME}
  DOCKER_INFLUXDB_INIT_PASSWORD: ${SECRET_INFLUXDB_INIT_PASSWORD}
  DOCKER_INFLUXDB_INIT_ORG: ${SECRET_INFLUXDB_INIT_ORG}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${SECRET_INFLUXDB_INIT_ADMIN_TOKEN}
