#!/bin/bash

echo "..........One-time InfluxDB2 setup for OpenHAB starting"

echo "..........Create active InfluxDB CLI configuration"
influx config create --config-name INIT --host-url http://${CONFIG_INFLUXDB_LB_ADDRESS}:8086 --org ${SECRET_INFLUXDB_INIT_ORG} --token ${SECRET_INFLUXDB_INIT_ADMIN_TOKEN} --active

echo "..........Check if OpenHAB user already exists"
influx user create -n ${SECRET_INFLUXDB_USER} -p ${SECRET_INFLUXDB_PASSWORD}
retVal=$?
if [ $retVal -ne 0 ]; then
  echo "..........User already exists, ignoring it"
fi

echo "..........Create authorizations for openHAB user"
influx auth create --user ${SECRET_INFLUXDB_USER} --read-authorizations --write-authorizations --read-buckets --write-buckets --read-dashboards --write-dashboards --read-tasks --write-tasks --read-telegrafs --write-telegrafs --read-users --write-users
retVal=$?
if [ $retVal -ne 0 ]; then
  echo "..........User authorization failed with return code $retVal"
fi

echo "..........One-time InfluxDB2 initialization for OpenHAB completed"

exit 0
