---
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
spec:
  completions: 1
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: influxdb-setup
          image: influxdb:2.7.11
          command: ["/bin/bash", "-c"]
          args: ["/bin/influxdb-init.sh"]
          volumeMounts:
            - name: influxdb-init
              mountPath: /bin/influxdb-init.sh
              readOnly: true
              subPath: influxdb-init.sh
      volumes:
        - name: influxdb-init
          configMap:
            defaultMode: 0700
            name: influxdb-init-script
