apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  ports:
    - name: influxdb-port
      port: 8086
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb-automation
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "${CONFIG_INFLUXDB_LB_ADDRESS}"
