# openhab.git:kustomize/base/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openhab-deploy
  labels:
    app.kubernetes.io/sops: enabled
resources:
  - services.yaml
  - ingressroute.yaml
  - secrets.yaml
  - volumes.yaml
  - configmaps.yaml
  - alloy-config.yaml
  - deployment.yaml
  