# openhab.git:kustomize/base/secrets.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: openhab
type: Opaque
stringData:
  openhab_fqdn: replace_me
  openhab_user: replace_me
  public_key_url: replace_me
